title = "Tech Paper"
content = "æŠ€æœ¯æŠ¥çº¸ï¼ŒåŒ…å«äº†æ—¥æŠ¥ã€å‘¨æŠ¥ã€æœˆæŠ¥ç­‰ç­‰"

[[groups]]
title = "IOS"

  [[groups.projects]]
  name = "è€å¸æœº iOS å‘¨æŠ¥"
  repo = "https://github.com/SwiftOldDriver/iOS-Weekly"
  website = "https://github.com/SwiftOldDriver/iOS-Weekly"
  content = """
> å¾ˆç²¾è‡´çš„ä¸€ä¸ª IOS æ—¥æŠ¥
"""
  createTime = 1_593_414_972_963
  updateTime = 1_593_414_972_963
  description = "ğŸ‡¨ğŸ‡³ è€å¸æœº iOS å‘¨æŠ¥"
